### ISSUE TITLE
Alternative to cram-md5

### ISSUE THREAD

**Issue by Alternativend** [corecode/dma#33] opened 2015-11-05 08:46 UTC
Hello,

im not an expert on this, but the IPFire project recently integrated your mailagent for notification purposes. 

Unfortunately some providers (including mine) didn´t support the cram-md5 login mechanism.

Do you see a chance to offer alternative login methods, so we can use them?

Thanks in advacne!

**Comment by corecode** [comment] 2015-11-05 17:01
Do you know which login methods are required?  You can also provide the host name for me to check by myself.

**Comment by Alternativend** [comment] 2015-11-09 06:48
My hosting company is schokokeks.org, they told me that they only support PLAIN and LOGIN.

**Comment by corecode** [comment] 2015-11-09 10:18
LOGIN is supported.  I'll need more details to see why the mail delivery does not work.  Could you please supply a log?

**Comment by mtremer** [comment] 2015-11-09 18:50
I can confirm that dma that is shipped in IPFire is working well with LOGIN.

However there is still the error message that is discussed in #15.

**Comment by Alternativend** [comment] 2015-11-10 07:45
I don´t know if you still need the logs, because it seems that Michael is working on a patch, but anyway:

<code>
Oct 29 14:09:42 ipfire dma[580015.9cec120]: using smarthost (missen.de:587)
Oct 29 14:09:42 ipfire dma[580015.9cec120]: trying remote delivery to missen.de [2a01:4f8:121:1ffe:1:1311:0:7cf] pref 0
Oct 29 14:09:42 ipfire dma[580015.9cec120]: connect to gs-asemissen.de [2a01:4f8:121:1ffe:1:1311:0:7cf] failed: Network is unreachable
Oct 29 14:09:42 ipfire dma[580015.9cec120]: trying remote delivery to missen.de [178.63.68.96] pref 0
Oct 29 14:09:42 ipfire dma[580015.9cec120]: SSL initialization successful
Oct 29 14:09:42 ipfire dma[580015.9cec120]: using SMTP authentication for user -backup@missen.de
Oct 29 14:09:43 ipfire dma[580015.9cec120]: remote delivery deferred: AUTH cram-md5 failed: 535 Authentication failed.
Oct 29 14:09:43 ipfire dma[580015.9cec120]: SMTP login not available. Trying without.
Oct 29 14:09:43 ipfire dma[580015.9cec120]: remote delivery to missen.de [178.63.68.96] failed after MAIL FROM: 535 Authentication required.
Oct 29 14:09:43 ipfire dma[580015.9cec120]: can not bounce a bounce message, discarding

</code>

**Comment by mtremer** [comment] 2015-11-10 22:49
Looks like this mail server does not support LOGIN to me or responds with something that DMA is not expecting.

**Comment by corecode** [comment] 2015-11-11 09:30
Extracted example handshake:

```
220 zucker.schokokeks.org ESMTP
EHLO test.0x2c.org
250-zucker.schokokeks.org Ok.
250-STARTTLS
250-XCOURIEREXTENSIONS
250-XVERP=Courier
250-XEXDATA
250-XSECURITY=NONE,STARTTLS
250-PIPELINING
250-8BITMIME
250-SIZE
250 DSN
STARTTLS^M
220 Ok
<TLS handshake>
EHLO test.0x2c.org
250-zucker.schokokeks.org Ok.
250-AUTH PLAIN LOGIN
250-XCOURIEREXTENSIONS
250-XVERP=Courier
250-XEXDATA
250-XSECURITY=NONE,STARTTLS
250-PIPELINING
250-8BITMIME
250-SIZE
250 DSN
```

**Comment by Alternativend** [comment] 2015-11-18 07:51
So where does this lead us?

**Comment by mtremer** [comment] 2015-11-18 11:06
Did you try to perform the LOGIN manually? Is this 100% sure that the server is handling that correctly?

**Comment by corecode** [comment] 2015-11-18 13:04
did you try with the patch from #34?

**Comment by Alternativend** [comment] 2015-11-23 07:48
@mtremer 
Could you update it in the IPFire branch, so i can test it with the patch included?

**Comment by mtremer** [comment] 2015-11-23 12:30
After I got a peer-review which says that the patch is okay, then yes...

**Comment by corecode** [comment] 2015-11-23 18:13
That makes this a chicken and egg problem.

**Comment by mtremer** [comment] 2015-11-23 21:32
Does it? I don't think so.

Would you merge this patch as it is if someone else confirms that it is working?

**Comment by Alternativend** [comment] 2015-12-08 11:05
So any progress on this? If you can tell me how to test the patch on my IPFire i will do what i can. 

So please let get this thing fixed!

**Comment by mtremer** [comment] 2015-12-10 16:42
I have imported this patch to our development build branch: http://git.ipfire.org/?p=ipfire-2.x.git;a=commitdiff;h=b1372c3befd4ba4541fad1a90200ae7c1628ff00

So it will appear in this night's nightly build. I believe that this is still completely untested and I have also not received a lot from upstream if this patch will ever be merged. So please send feedback, otherwise I will revert this change soon.

**Comment by Alternativend** [comment] 2015-12-14 07:17
Im at the dev-branch with two machines, but i can´t see any updates for dma. What am im doing wrong?

**Comment by mtremer** [comment] 2015-12-15 14:15
You will need to download the ISO image and install the system from that.

http://nightly.ipfire.org/next/latest/

**Comment by mtremer** [comment] 2015-12-15 19:58
Matthias has compiled this for you: http://forum.ipfire.org/viewtopic.php?f=50&t=15009#p92764

**Comment by kgaughan** [comment] 2018-03-21 02:41
Given #34 has been merged, I'd say this issue can be closed.

**Comment by corecode** [comment] 2018-03-21 09:42
thanks!

**Closed by corecode** 2018-03-21 09:42 UTC
